### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by adbenitez** [arikwex/runekeeper#1]
hi, nice game! is this open source? if so could you please add a license file? I am interested into porting it to https://webxdc.org (sandboxed web apps in a chat)

or if you are interested into porting it yourself and publishing it in the WebXDC app store, read here: https://delta.chat/en/2023-08-11-xstore#how-can-i-submit-my-own-webxdc-app-to-xstore

have a nice day!

**Comment by arikwex** [comment]
added license -- have fun

**Comment by adbenitez** [comment]
thanks a lot! :heart:

**Comment by adbenitez** [comment]
hi @arikwex, your game got accepted in the WebXDC apps store! :tada: 

I added highscores-sharing to it so when groups of friend play it in a chat, a system message is displayed in the chat notifying everyone that "Foo scored X in Runekeeper" so it is kinda multiplayer arcade!

![image](https://github.com/arikwex/runekeeper/assets/24558636/f22f449b-5221-43e5-83b1-4c6af9a412a1)

![image](https://github.com/arikwex/runekeeper/assets/24558636/6c74e73e-0c75-4b46-a50b-30312dd1a9c2)
